<?php

namespace OutilBundle\Repository;

/**
 * Categorie_OutilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Categorie_OutilRepository extends \Doctrine\ORM\EntityRepository
{
}
