<?php

namespace OffreBundle\Repository;

/**
 * categorieTechnologieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorieTechnologieRepository extends \Doctrine\ORM\EntityRepository
{
}
