<?php

namespace OffreBundle\Repository;

/**
 * clientParticipeProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class freelancerParticipeProjetRepository extends \Doctrine\ORM\EntityRepository
{
}
