<?php

namespace OffreBundle\Repository;

/**
 * freelancerDemandeProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class freelancerDemandeProjetRepository extends \Doctrine\ORM\EntityRepository
{
}
