offre_freelancer_demande_projet:
    resource: "@OffreBundle/Controller/FreelancerDemandeProjetController.php"
    type:     annotation

offre_technologie:
    resource: "@OffreBundle/Controller/TechnologieController.php"
    type:     annotation

offre_categorie_technologie:
    resource: "@OffreBundle/Controller/CategorieTechnologieController.php"
    type:     annotation

offre_projet:
    resource: "@OffreBundle/Controller/ProjetController.php"
    type:     annotation
offre:
    resource: "@OffreBundle/Resources/config/routing.yml"
    prefix:   /

app_booking:
    resource: "@AppBundle/Controller/BookingController.php"
    type:     annotation

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /message

visiteur:
    resource: "@VisiteurBundle/Resources/config/routing.yml"
    prefix:   /

freelancer:
    resource: "@FreelancerBundle/Resources/config/routing.yml"
    prefix:   /

client:
    resource: "@ClientBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

toiba_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yaml"

